PressAnyKey/Controllers/AmigoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PressAnyKey.Data;
using PressAnyKey.Models;

namespace PressAnyKey.Controllers
{
    public class AmigoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AmigoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Amigo
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Amigo.Include(a => a.UsuarioDestinatario).Include(a => a.UsuarioRemetente);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Amigo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amigo = await _context.Amigo
                .Include(a => a.UsuarioDestinatario)
                .Include(a => a.UsuarioRemetente)
                .FirstOrDefaultAsync(m => m.IdRemetente == id);
            if (amigo == null)
            {
                return NotFound();
            }

            return View(amigo);
        }

        // GET: Amigo/Create
        public IActionResult Create()
        {
            ViewData["IdDestinatario"] = new SelectList(_context.Usuario, "Id", "Id");
            ViewData["IdRemetente"] = new SelectList(_context.Usuario, "Id", "Id");
            return View();
        }

        // POST: Amigo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRemetente,IdDestinatario")] Amigo amigo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(amigo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDestinatario"] = new SelectList(_context.Usuario, "Id", "Id", amigo.IdDestinatario);
            ViewData["IdRemetente"] = new SelectList(_context.Usuario, "Id", "Id", amigo.IdRemetente);
            return View(amigo);
        }

        // GET: Amigo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amigo = await _context.Amigo.FindAsync(id);
            if (amigo == null)
            {
                return NotFound();
            }
            ViewData["IdDestinatario"] = new SelectList(_context.Usuario, "Id", "Id", amigo.IdDestinatario);
            ViewData["IdRemetente"] = new SelectList(_context.Usuario, "Id", "Id", amigo.IdRemetente);
            return View(amigo);
        }

        // POST: Amigo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRemetente,IdDestinatario")] Amigo amigo)
        {
            if (id != amigo.IdRemetente)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(amigo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AmigoExists(amigo.IdRemetente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDestinatario"] = new SelectList(_context.Usuario, "Id", "Id", amigo.IdDestinatario);
            ViewData["IdRemetente"] = new SelectList(_context.Usuario, "Id", "Id", amigo.IdRemetente);
            return View(amigo);
        }

        // GET: Amigo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amigo = await _context.Amigo
                .Include(a => a.UsuarioDestinatario)
                .Include(a => a.UsuarioRemetente)
                .FirstOrDefaultAsync(m => m.IdDestinatario == id);
            if (amigo == null)
            {
                return NotFound();
            }

            return View(amigo);
        }

        // POST: Amigo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var IdentityUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var IdentityUser = _context.Users.FirstOrDefault(u => u.Id == IdentityUserId);
            var usuarioLogado = _context.Usuario.FirstOrDefault(u => u.IdentityUser.Id == IdentityUserId);
            var amigo = await _context.Amigo.FindAsync(usuarioLogado.Id, id);
            _context.Amigo.Remove(amigo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Feed");
        }

        private bool AmigoExists(int id)
        {
            return _context.Amigo.Any(e => e.IdRemetente == id);
        }
        public async Task<IActionResult> Seguir(int id)
        {
            var amigo = new Amigo();
            if (ModelState.IsValid)
            {
                var IdentityUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var IdentityUser = _context.Users.FirstOrDefault(u => u.Id == IdentityUserId);
                var usuarioLogado = _context.Usuario.FirstOrDefault(u => u.IdentityUser.Id == IdentityUserId);
                var usuarioAmigo = _context.Usuario.FirstOrDefault(u => u.Id == id);
                amigo.IdRemetente = usuarioLogado.Id;
                amigo.IdDestinatario = id;
                amigo.UsuarioRemetente = usuarioLogado;
                amigo.UsuarioDestinatario = usuarioAmigo;
                _context.Add(amigo);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Feed");
            }
            return View(amigo);
        }
        public IActionResult ListAmigo()
        {
            var IdentityUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var IdentityUser = _context.Users.FirstOrDefault(u => u.Id == IdentityUserId);
            var usuarioLogado = _context.Usuario.FirstOrDefault(u => u.IdentityUser.Id == IdentityUserId);
            var applicationDbContext = _context.Amigo.Include(a => a.UsuarioDestinatario).Include(a => a.UsuarioRemetente);
            ICollection<Usuario> usuarios = new List<Usuario>();
            foreach (var a in applicationDbContext)
                if (a.UsuarioRemetente == usuarioLogado)
                    usuarios.Add(a.UsuarioDestinatario);

            return View(usuarios);
        }
    }
}

PressAnyKey/Controllers/FeedController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PressAnyKey.Data;
using PressAnyKey.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PressAnyKey.Controllers
{
    public class FeedController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FeedController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Feed
        public IActionResult Index()
        {
            var IdentityUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var IdentityUser = _context.Users.FirstOrDefault(u => u.Id == IdentityUserId);
            var usuarioLogado = _context.Usuario.FirstOrDefault(u => u.IdentityUser.Id == IdentityUserId);
            if (usuarioLogado == null)
                return RedirectToAction("Create", "Usuario");

            return View();
        }

        // GET: Feed/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feed = await _context.Feed
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feed == null)
            {
                return NotFound();
            }

            return View(feed);
        }

        // GET: Feed/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Feed/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id")] Feed feed)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feed);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(feed);
        }

        // GET: Feed/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feed = await _context.Feed.FindAsync(id);
            if (feed == null)
            {
                return NotFound();
            }
            return View(feed);
        }

        // POST: Feed/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id")] Feed feed)
        {
            if (id != feed.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feed);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedExists(feed.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(feed);
        }

        // GET: Feed/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feed = await _context.Feed
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feed == null)
            {
                return NotFound();
            }

            return View(feed);
        }

        // POST: Feed/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var feed = await _context.Feed.FindAsync(id);
            _context.Feed.Remove(feed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedExists(int id)
        {
            return _context.Feed.Any(e => e.Id == id);
        }
    }
}

PressAnyKey/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PressAnyKey.Data;
using PressAnyKey.Models;

namespace PressAnyKey.Controllers
{
    public class PerfilController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PerfilController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var IdentityUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var IdentityUser = _context.Users.FirstOrDefault(u => u.Id == IdentityUserId);
            var usuarioLogado = _context.Usuario.FirstOrDefault(u => u.IdentityUser.Id == IdentityUserId);
            if (usuarioLogado == null)
                return RedirectToAction("Create", "Usuario");
            return View();

            /*List<Postagem> postagens = new List<Postagem>();
            try
            {
                var IdentityUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var IdentityUser = _context.Users.FirstOrDefault(u => u.Id == IdentityUserId);
                var usuarioLogado = _context.Usuario.FirstOrDefault(u => u.IdentityUser.Id == IdentityUserId);
                if (usuarioLogado == null)
                    return RedirectToAction("Create", "Usuario");
                var amigos = _context.Amigo.Include(a => a.UsuarioDestinatario).Include(a => a.UsuarioRemetente);
                var feed = _context.Postagem.ToList();
                if (usuarioLogado.Postagens != null)
                    postagens.AddRange(usuarioLogado.Postagens);
                foreach (var amigo in amigos)
                {
                    if (amigo.UsuarioRemetente == usuarioLogado)
                        if (amigo.UsuarioDestinatario.Postagens != null)
                            postagens.AddRange(amigo.UsuarioDestinatario.Postagens);
                }
                postagens.Sort((x, y) => y.DataPostagem.CompareTo(x.DataPostagem));
                return View(postagens);
            }
            catch (System.Exception)
            {
                return RedirectToAction("Index", "Home");
            }*/
        }
    }
}

PressAnyKey/Views/Shared/_FeedLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/js/index.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gelasio&display=swap" rel="stylesheet">

</head>
<body style="background: #18262b;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-customc1 box-shadow mb-3">
            <div class="container">
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Feed" asp-action="Index"><img style="width: 80%;" src="~/images/Logo5.png" /></a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="width: 80%;" src="~/images/Logo5.png" /></a>
                }
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_FeedPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div style="display: flex;">
        <div style="width: 25%; border: solid 1px #0000001f; border-width: 0px 1px 0px 0px;" class="ff-Raleway">
            <div style="position: sticky; top: 0;padding: 4px;">
                <div id="Feed-Area">
                    <ul class="list-group">
                        <a asp-controller="Perfil" asp-action="Index" class="nounderline">
                            <li style="padding: .3rem 0.78rem;" class="custom-list-group1">
                                Meu perfil
                            </li>
                        </a>
                        <a asp-controller="Feed" asp-action="Index" class="nounderline">
                            <li style="padding: .3rem 0.78rem;" class="custom-list-group1">
                                Feed de Noticias
                            </li>
                        </a>
                    </ul>
                </div>
                <hr />
                <div id="ConfConta" class="ff-Raleway">
                    <ul class="list-group">
                        <li style="padding: .3rem 0.78rem;" class="custom-list-group1">

                            <p class="text-light-c2">Configurações</p>

                            <ul class="list-group">
                                <a href="#" class="nounderline">
                                    <li style="padding: .3rem 0.78rem;" class="custom-list-group1">
                                        Alterar Informações pessoais
                                    </li>
                                </a>
                                <a class="nounderline" href="#">
                                    <li style="padding: .3rem 0.78rem;" class="custom-list-group1">
                                        Alterar segurança
                                    </li>
                                </a>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        @RenderBody()
    </div>
    <footer style="position: inherit !important; background:#ffffff0d;" class="custom-bt footer text-muted">
        <div style="padding: 16px 9%;">
            &copy; 2019 - PressAnyKey - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>

PressAnyKey/Views/Shared/_FeedPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <!--<li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
    </li>-->
        <a class="nounderline" asp-controller="Perfil" asp-action="Index">
            <li class="nav-item">
                <button class="nav-link btn btn-link thead-light">Perfil</button>
            </li>
        </a>
        <li class="nav-item">
            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                <button type="submit" class="nav-link btn btn-link thead-light">Logout</button>
            </form>
        </li>
        <!--<li class="nav-item">
        <a asp-controller="Usuario" asp-action  ="Create">Perfil</a>
    </li>-->
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
        </li>
    }
    </ul>

PressAnyKey/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PressAnyKey</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
</head>
<body style="background: #18262b;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-customc1 box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index"><img style="width: 80%;" src="~/images/Logo5.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <!--<li class="nav-item">
                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>-->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="position-relative">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="margin-top: 3%;" class="border-top text-muted">
        <div class="container">
            &copy; 2019 - PressAnyKey - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/home.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PressAnyKey/Views/Shared/_PerfilLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/js/index.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gelasio&display=swap" rel="stylesheet">

</head>
<body style="background: #18262b;">
    <div class="container">
        <div style="height: 15pc;background: linear-gradient(#3f8258, #225b51);"></div>
        <header style="padding: 0px;border-radius: 0px 0px 8px 8px;" class="navbar navbar-expand-sm bg-customc1 navbar-dark">
            <div class="perfil-img-column">
                <a href="#">
                    <div class="perfil-img"></div>
                </a>
            </div>

            <div class="container navbar-nav">
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="nounderline nav-item" asp-area="" asp-controller="Feed" asp-action="Index"><img style="width: 80%;padding: 4px;" src="~/images/Logo5.png" /></a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="width: 80%;padding: 4px;" src="~/images/Logo5.png" /></a>
                }
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_PerfilPartial" />
                </div>
            </div>
        </header>
    </div>
    <div class="container">
        @RenderBody()
    </div>

    <footer style="position: inherit !important; background:#ffffff0d;" class="custom-bt footer text-muted">
        <div style="padding: 16px 9%;">
            &copy; 2019 - PressAnyKey - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>

PressAnyKey/Views/Shared/_PerfilPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

    <ul class="navbar-nav">
        @if (SignInManager.IsSignedIn(User))
        {
            <!--<li class="nav-item">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
        </li>-->

            <a class="nounderline" asp-controller="Perfil" asp-action="Index">
                <li class="nav-item">
                    <button class="nav-link btn btn-link thead-light">Perfil</button>
                </li>
            </a>
            <a class="nounderline" asp-controller="Feed" asp-action="Index">
                <li class="nav-item">
                    <button class="nav-link btn btn-link thead-light">Feed</button>
                </li>
            </a>
            <a class="nounderline" asp-controller="Amigo" asp-action="ListAmigo">
                <li class="nav-item">
                    <button class="nav-link btn btn-link thead-light">Amigos</button>
                </li>
            </a>
            <li class="nav-item">
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button type="submit" class="nav-link btn btn-link thead-light">Logout</button>
                </form>
            </li>
            <!--<li class="nav-item">
            <a asp-controller="Usuario" asp-action  ="Create">Perfil</a>
        </li>-->
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
            </li>
        }
    </ul>